use rxbyak::*;

/// Helper: assemble instructions and return the generated bytes.
fn assemble(f: impl FnOnce(&mut CodeAssembler) -> Result<()>) -> Vec<u8> {
    let mut asm = CodeAssembler::new(4096).unwrap();
    f(&mut asm).unwrap();
    asm.code().to_vec()
}

#[test]
fn test_nop() {
    let code = assemble(|a| a.nop());
    assert_eq!(code, [0x90]);
}

#[test]
fn test_ret() {
    let code = assemble(|a| a.ret());
    assert_eq!(code, [0xC3]);
}

#[test]
fn test_ret_imm() {
    let code = assemble(|a| a.ret_imm(8));
    assert_eq!(code, [0xC2, 0x08, 0x00]);
}

#[test]
fn test_int3() {
    let code = assemble(|a| a.int3());
    assert_eq!(code, [0xCC]);
}

#[test]
fn test_push_pop_rax() {
    let code = assemble(|a| {
        a.push(RAX)?;
        a.pop(RAX)
    });
    assert_eq!(code, [0x50, 0x58]);
}

#[test]
fn test_push_pop_r8() {
    let code = assemble(|a| {
        a.push(R8)?;
        a.pop(R8)
    });
    assert_eq!(code, [0x41, 0x50, 0x41, 0x58]);
}

#[test]
fn test_push_imm8() {
    let code = assemble(|a| a.push_imm(42));
    assert_eq!(code, [0x6A, 42]);
}

#[test]
fn test_push_imm32() {
    let code = assemble(|a| a.push_imm(0x12345678));
    assert_eq!(code, [0x68, 0x78, 0x56, 0x34, 0x12]);
}

#[test]
fn test_mov_reg_reg() {
    // mov eax, ecx → 89 C8
    let code = assemble(|a| a.mov(EAX, ECX));
    assert_eq!(code, [0x89, 0xC8]);
}

#[test]
fn test_mov_rax_rcx() {
    // mov rax, rcx → 48 89 C8
    let code = assemble(|a| a.mov(RAX, RCX));
    assert_eq!(code, [0x48, 0x89, 0xC8]);
}

#[test]
fn test_mov_reg_imm32() {
    // mov eax, 42 → B8 2A 00 00 00
    let code = assemble(|a| a.mov(EAX, 42i32));
    assert_eq!(code, [0xB8, 0x2A, 0x00, 0x00, 0x00]);
}

#[test]
fn test_mov_al_imm8() {
    // mov al, 0xFF → B0 FF
    let code = assemble(|a| a.mov(AL, 0xFFi32));
    assert_eq!(code, [0xB0, 0xFF]);
}

#[test]
fn test_mov_rax_imm32_zero_ext() {
    // mov rax, 42 → optimized to mov eax, 42 (zero-extends to 64-bit)
    // → B8 2A 00 00 00
    let code = assemble(|a| a.mov(RAX, 42i32));
    assert_eq!(code, [0xB8, 0x2A, 0x00, 0x00, 0x00]);
}

#[test]
fn test_add_eax_ecx() {
    // add eax, ecx → 01 C8
    let code = assemble(|a| a.add(EAX, ECX));
    assert_eq!(code, [0x01, 0xC8]);
}

#[test]
fn test_add_eax_imm8() {
    // add eax, 1 → 83 C0 01
    let code = assemble(|a| a.add(EAX, 1i32));
    assert_eq!(code, [0x83, 0xC0, 0x01]);
}

#[test]
fn test_add_eax_imm32() {
    // add eax, 0x12345678 → 05 78 56 34 12 (short form for eax)
    let code = assemble(|a| a.add(EAX, 0x12345678i32));
    assert_eq!(code, [0x05, 0x78, 0x56, 0x34, 0x12]);
}

#[test]
fn test_sub_rax_rcx() {
    // sub rax, rcx → 48 29 C8
    let code = assemble(|a| a.sub(RAX, RCX));
    assert_eq!(code, [0x48, 0x29, 0xC8]);
}

#[test]
fn test_xor_eax_eax() {
    // xor eax, eax → 31 C0
    let code = assemble(|a| a.xor_(EAX, EAX));
    assert_eq!(code, [0x31, 0xC0]);
}

#[test]
fn test_cmp_eax_imm() {
    // cmp eax, 0 → 83 F8 00
    let code = assemble(|a| a.cmp(EAX, 0i32));
    assert_eq!(code, [0x83, 0xF8, 0x00]);
}

#[test]
fn test_inc_ecx() {
    // inc ecx → FF C1
    let code = assemble(|a| a.inc(ECX));
    assert_eq!(code, [0xFF, 0xC1]);
}

#[test]
fn test_dec_rdx() {
    // dec rdx → 48 FF CA
    let code = assemble(|a| a.dec(RDX));
    assert_eq!(code, [0x48, 0xFF, 0xCA]);
}

#[test]
fn test_mov_mem_reg() {
    // mov [rax], ecx → 89 08
    let code = assemble(|a| a.mov(dword_ptr(RAX.into()), ECX));
    assert_eq!(code, [0x89, 0x08]);
}

#[test]
fn test_mov_mem_disp8() {
    // mov [rax+0x10], ecx → 89 48 10
    let code = assemble(|a| a.mov(dword_ptr(RAX + 0x10), ECX));
    assert_eq!(code, [0x89, 0x48, 0x10]);
}

#[test]
fn test_mov_reg_mem() {
    // mov ecx, [rax] → 8B 08
    let code = assemble(|a| a.mov(ECX, dword_ptr(RAX.into())));
    assert_eq!(code, [0x8B, 0x08]);
}

#[test]
fn test_lea() {
    // lea rax, [rcx+rdx*4+0x10] → 48 8D 44 91 10
    let code = assemble(|a| a.lea(RAX, ptr(RCX + RDX * 4 + 0x10)));
    assert_eq!(code, [0x48, 0x8D, 0x44, 0x91, 0x10]);
}

#[test]
fn test_shl_eax_1() {
    // shl eax, 1 → D1 E0
    let code = assemble(|a| a.shl(EAX, 1));
    assert_eq!(code, [0xD1, 0xE0]);
}

#[test]
fn test_shl_eax_4() {
    // shl eax, 4 → C1 E0 04
    let code = assemble(|a| a.shl(EAX, 4));
    assert_eq!(code, [0xC1, 0xE0, 0x04]);
}

#[test]
fn test_shr_rax_1() {
    // shr rax, 1 → 48 D1 E8
    let code = assemble(|a| a.shr(RAX, 1));
    assert_eq!(code, [0x48, 0xD1, 0xE8]);
}

#[test]
fn test_shl_eax_cl() {
    // shl eax, cl → D3 E0
    let code = assemble(|a| a.shl_cl(EAX));
    assert_eq!(code, [0xD3, 0xE0]);
}

#[test]
fn test_shr_rax_cl() {
    // shr rax, cl → 48 D3 E8
    let code = assemble(|a| a.shr_cl(RAX));
    assert_eq!(code, [0x48, 0xD3, 0xE8]);
}

#[test]
fn test_sar_ebx_cl() {
    // sar ebx, cl → D3 FB
    let code = assemble(|a| a.sar_cl(EBX));
    assert_eq!(code, [0xD3, 0xFB]);
}

#[test]
fn test_rol_ecx_cl() {
    // rol ecx, cl → D3 C1
    let code = assemble(|a| a.rol_cl(ECX));
    assert_eq!(code, [0xD3, 0xC1]);
}

#[test]
fn test_ror_rdx_cl() {
    // ror rdx, cl → 48 D3 CA
    let code = assemble(|a| a.ror_cl(RDX));
    assert_eq!(code, [0x48, 0xD3, 0xCA]);
}

#[test]
fn test_bt_eax_imm() {
    // bt eax, 5 → 0F BA E0 05
    let code = assemble(|a| a.bt_imm(EAX, 5));
    assert_eq!(code, [0x0F, 0xBA, 0xE0, 0x05]);
}

#[test]
fn test_bts_rax_imm() {
    // bts rax, 7 → 48 0F BA E8 07
    let code = assemble(|a| a.bts_imm(RAX, 7));
    assert_eq!(code, [0x48, 0x0F, 0xBA, 0xE8, 0x07]);
}

#[test]
fn test_btr_ecx_imm() {
    // btr ecx, 3 → 0F BA F1 03
    let code = assemble(|a| a.btr_imm(ECX, 3));
    assert_eq!(code, [0x0F, 0xBA, 0xF1, 0x03]);
}

#[test]
fn test_btc_rdx_imm() {
    // btc rdx, 10 → 48 0F BA FA 0A
    let code = assemble(|a| a.btc_imm(RDX, 10));
    assert_eq!(code, [0x48, 0x0F, 0xBA, 0xFA, 0x0A]);
}

#[test]
fn test_label_forward_jmp() {
    let code = assemble(|a| {
        let label = a.create_label();
        a.jmp(&label, JmpType::Near)?;
        a.nop()?;
        a.nop()?;
        a.bind(&label)?;
        a.ret()
    });
    // jmp near (5 bytes) → E9 02 00 00 00
    // nop → 90
    // nop → 90
    // ret → C3
    assert_eq!(code, [0xE9, 0x02, 0x00, 0x00, 0x00, 0x90, 0x90, 0xC3]);
}

#[test]
fn test_label_backward_jmp() {
    let code = assemble(|a| {
        let label = a.create_label();
        a.bind(&label)?;
        a.nop()?;
        a.jmp(&label, JmpType::Near)
    });
    // nop → 90
    // jmp near → E9 FA FF FF FF (-6 = back to start, displacement = target - end_of_jmp)
    assert_eq!(code, [0x90, 0xE9, 0xFA, 0xFF, 0xFF, 0xFF]);
}

#[test]
fn test_jz_forward() {
    let code = assemble(|a| {
        let label = a.create_label();
        a.cmp(EAX, 0i32)?;
        a.jz(&label, JmpType::Near)?;
        a.nop()?;
        a.bind(&label)?;
        a.ret()
    });
    // cmp eax, 0  → 83 F8 00
    // jz near     → 0F 84 01 00 00 00
    // nop         → 90
    // ret         → C3
    assert_eq!(code, [0x83, 0xF8, 0x00, 0x0F, 0x84, 0x01, 0x00, 0x00, 0x00, 0x90, 0xC3]);
}

#[test]
fn test_mov_r8_r9() {
    // mov r8, r9 → 4D 89 C8
    let code = assemble(|a| a.mov(R8, R9));
    assert_eq!(code, [0x4D, 0x89, 0xC8]);
}

#[test]
fn test_mov_rsp_offset() {
    // mov [rsp+8], rax → 48 89 44 24 08
    let code = assemble(|a| a.mov(qword_ptr(RSP + 8), RAX));
    assert_eq!(code, [0x48, 0x89, 0x44, 0x24, 0x08]);
}

#[test]
fn test_mov_rbp_offset() {
    // mov [rbp-8], rax → 48 89 45 F8
    let code = assemble(|a| a.mov(qword_ptr(RBP - 8), RAX));
    assert_eq!(code, [0x48, 0x89, 0x45, 0xF8]);
}

#[test]
fn test_cdq_cqo() {
    let code = assemble(|a| {
        a.cdq()?;
        a.cqo()
    });
    assert_eq!(code, [0x99, 0x48, 0x99]);
}

#[test]
fn test_test_eax_imm() {
    // test eax, 0xFF → A9 FF 00 00 00
    let code = assemble(|a| a.test(EAX, 0xFFi32));
    assert_eq!(code, [0xA9, 0xFF, 0x00, 0x00, 0x00]);
}

#[test]
fn test_neg_eax() {
    // neg eax → F7 D8
    let code = assemble(|a| a.neg(EAX));
    assert_eq!(code, [0xF7, 0xD8]);
}

#[test]
fn test_not_eax() {
    // not eax → F7 D0
    let code = assemble(|a| a.not_(EAX));
    assert_eq!(code, [0xF7, 0xD0]);
}

#[test]
fn test_or_and_xor() {
    let code = assemble(|a| {
        a.or_(EAX, ECX)?;    // 09 C8
        a.and_(EAX, ECX)?;   // 21 C8
        a.xor_(EAX, ECX)     // 31 C8
    });
    assert_eq!(code, [0x09, 0xC8, 0x21, 0xC8, 0x31, 0xC8]);
}

#[test]
fn test_imul_eax_ecx() {
    // imul eax, ecx → 0F AF C1
    let code = assemble(|a| a.imul(EAX, ECX));
    assert_eq!(code, [0x0F, 0xAF, 0xC1]);
}

#[test]
fn test_complex_address() {
    // mov eax, [rbx+rsi*8+0x100]
    // → 8B 84 F3 00 01 00 00
    let code = assemble(|a| a.mov(EAX, dword_ptr(RBX + RSI * 8 + 0x100)));
    assert_eq!(code, [0x8B, 0x84, 0xF3, 0x00, 0x01, 0x00, 0x00]);
}

#[test]
fn test_push_pop_16bit() {
    let code = assemble(|a| {
        a.push(AX)?;
        a.pop(AX)
    });
    assert_eq!(code, [0x66, 0x50, 0x66, 0x58]);
}

// ── CRC32 ────────────────────────────────────────────────────

#[test]
fn test_crc32_r32_r8() {
    // crc32 eax, bl → F2 0F 38 F0 C3
    let code = assemble(|a| a.crc32(EAX, BL));
    assert_eq!(code, [0xF2, 0x0F, 0x38, 0xF0, 0xC3]);
}

#[test]
fn test_crc32_r32_r16() {
    // crc32 eax, cx → 66 F2 0F 38 F1 C1
    let code = assemble(|a| a.crc32(EAX, CX));
    assert_eq!(code, [0x66, 0xF2, 0x0F, 0x38, 0xF1, 0xC1]);
}

#[test]
fn test_crc32_r32_r32() {
    // crc32 eax, ecx → F2 0F 38 F1 C1
    let code = assemble(|a| a.crc32(EAX, ECX));
    assert_eq!(code, [0xF2, 0x0F, 0x38, 0xF1, 0xC1]);
}

#[test]
fn test_crc32_r64_r8() {
    // crc32 rax, bl → F2 48 0F 38 F0 C3
    let code = assemble(|a| a.crc32(RAX, BL));
    assert_eq!(code, [0xF2, 0x48, 0x0F, 0x38, 0xF0, 0xC3]);
}

#[test]
fn test_crc32_r64_r64() {
    // crc32 rax, rcx → F2 48 0F 38 F1 C1
    let code = assemble(|a| a.crc32(RAX, RCX));
    assert_eq!(code, [0xF2, 0x48, 0x0F, 0x38, 0xF1, 0xC1]);
}

#[test]
fn test_crc32_bad_size() {
    // crc32 r64, r32 should fail
    let mut asm = CodeAssembler::new(4096).unwrap();
    assert!(asm.crc32(RAX, ECX).is_err());
    // crc32 r64, r16 should fail
    let mut asm = CodeAssembler::new(4096).unwrap();
    assert!(asm.crc32(RAX, CX).is_err());
}

// ── PSLLDQ / PSRLDQ ──────────────────────────────────────────

#[test]
fn test_pslldq() {
    // pslldq xmm0, 4 → 66 0F 73 F8 04
    let code = assemble(|a| a.pslldq(XMM0, 4));
    assert_eq!(code, [0x66, 0x0F, 0x73, 0xF8, 0x04]);
}

#[test]
fn test_psrldq() {
    // psrldq xmm0, 4 → 66 0F 73 D8 04
    let code = assemble(|a| a.psrldq(XMM0, 4));
    assert_eq!(code, [0x66, 0x0F, 0x73, 0xD8, 0x04]);
}

#[test]
fn test_pslldq_xmm8() {
    // pslldq xmm8, 1 → 66 41 0F 73 F8 01
    let code = assemble(|a| a.pslldq(XMM8, 1));
    assert_eq!(code, [0x66, 0x41, 0x0F, 0x73, 0xF8, 0x01]);
}

#[test]
fn test_psrldq_xmm8() {
    // psrldq xmm8, 1 → 66 41 0F 73 D8 01
    let code = assemble(|a| a.psrldq(XMM8, 1));
    assert_eq!(code, [0x66, 0x41, 0x0F, 0x73, 0xD8, 0x01]);
}

#[cfg(target_os = "windows")]
#[test]
fn test_jit_execution() {
    let mut asm = CodeAssembler::new(4096).unwrap();
    // Simple function: return 42
    // mov eax, 42
    // ret
    asm.mov(EAX, 42i32).unwrap();
    asm.ret().unwrap();
    asm.ready().unwrap();

    let f: extern "C" fn() -> i32 = unsafe { asm.get_code() };
    assert_eq!(f(), 42);
}
