use rxbyak::*;

/// Helper: assemble instructions and return the generated bytes.
fn assemble(f: impl FnOnce(&mut CodeAssembler) -> Result<()>) -> Vec<u8> {
    let mut asm = CodeAssembler::new(4096).unwrap();
    f(&mut asm).unwrap();
    asm.code().to_vec()
}

// ─── SSE Arithmetic ────────────────────────────────────────────

#[test]
fn test_addps() {
    // addps xmm0, xmm1 → 0F 58 C1
    let code = assemble(|a| a.addps(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x58, 0xC1]);
}

#[test]
fn test_addpd() {
    // addpd xmm0, xmm1 → 66 0F 58 C1
    let code = assemble(|a| a.addpd(XMM0, XMM1));
    assert_eq!(code, [0x66, 0x0F, 0x58, 0xC1]);
}

#[test]
fn test_addss() {
    // addss xmm0, xmm1 → F3 0F 58 C1
    let code = assemble(|a| a.addss(XMM0, XMM1));
    assert_eq!(code, [0xF3, 0x0F, 0x58, 0xC1]);
}

#[test]
fn test_addsd() {
    // addsd xmm0, xmm1 → F2 0F 58 C1
    let code = assemble(|a| a.addsd(XMM0, XMM1));
    assert_eq!(code, [0xF2, 0x0F, 0x58, 0xC1]);
}

#[test]
fn test_subps() {
    // subps xmm0, xmm1 → 0F 5C C1
    let code = assemble(|a| a.subps(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x5C, 0xC1]);
}

#[test]
fn test_mulps() {
    // mulps xmm0, xmm1 → 0F 59 C1
    let code = assemble(|a| a.mulps(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x59, 0xC1]);
}

#[test]
fn test_divps() {
    // divps xmm0, xmm1 → 0F 5E C1
    let code = assemble(|a| a.divps(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x5E, 0xC1]);
}

// ─── SSE Logic ─────────────────────────────────────────────────

#[test]
fn test_xorps() {
    // xorps xmm0, xmm0 → 0F 57 C0
    let code = assemble(|a| a.xorps(XMM0, XMM0));
    assert_eq!(code, [0x0F, 0x57, 0xC0]);
}

#[test]
fn test_xorpd() {
    // xorpd xmm0, xmm1 → 66 0F 57 C1
    let code = assemble(|a| a.xorpd(XMM0, XMM1));
    assert_eq!(code, [0x66, 0x0F, 0x57, 0xC1]);
}

#[test]
fn test_andps() {
    // andps xmm0, xmm1 → 0F 54 C1
    let code = assemble(|a| a.andps(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x54, 0xC1]);
}

#[test]
fn test_orps() {
    // orps xmm0, xmm1 → 0F 56 C1
    let code = assemble(|a| a.orps(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x56, 0xC1]);
}

// ─── SSE Misc ──────────────────────────────────────────────────

#[test]
fn test_sqrtps() {
    // sqrtps xmm0, xmm1 → 0F 51 C1
    let code = assemble(|a| a.sqrtps(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x51, 0xC1]);
}

#[test]
fn test_sqrtsd() {
    // sqrtsd xmm2, xmm3 → F2 0F 51 D3
    let code = assemble(|a| a.sqrtsd(XMM2, XMM3));
    assert_eq!(code, [0xF2, 0x0F, 0x51, 0xD3]);
}

#[test]
fn test_comiss() {
    // comiss xmm0, xmm1 → 0F 2F C1
    let code = assemble(|a| a.comiss(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x2F, 0xC1]);
}

#[test]
fn test_comisd() {
    // comisd xmm0, xmm1 → 66 0F 2F C1
    let code = assemble(|a| a.comisd(XMM0, XMM1));
    assert_eq!(code, [0x66, 0x0F, 0x2F, 0xC1]);
}

// ─── SSE Data Movement ────────────────────────────────────────

#[test]
fn test_movaps_reg_reg() {
    // movaps xmm0, xmm1 → 0F 28 C1
    let code = assemble(|a| a.movaps(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x28, 0xC1]);
}

#[test]
fn test_movups_reg_reg() {
    // movups xmm0, xmm1 → 0F 10 C1
    let code = assemble(|a| a.movups(XMM0, XMM1));
    assert_eq!(code, [0x0F, 0x10, 0xC1]);
}

#[test]
fn test_movapd_reg_reg() {
    // movapd xmm0, xmm1 → 66 0F 28 C1
    let code = assemble(|a| a.movapd(XMM0, XMM1));
    assert_eq!(code, [0x66, 0x0F, 0x28, 0xC1]);
}

#[test]
fn test_movdqa_reg_reg() {
    // movdqa xmm0, xmm1 → 66 0F 6F C1
    let code = assemble(|a| a.movdqa(XMM0, XMM1));
    assert_eq!(code, [0x66, 0x0F, 0x6F, 0xC1]);
}

#[test]
fn test_movdqu_reg_reg() {
    // movdqu xmm0, xmm1 → F3 0F 6F C1
    let code = assemble(|a| a.movdqu(XMM0, XMM1));
    assert_eq!(code, [0xF3, 0x0F, 0x6F, 0xC1]);
}

// ─── SSE Integer ───────────────────────────────────────────────

#[test]
fn test_paddd() {
    // paddd xmm0, xmm1 → 66 0F FE C1
    let code = assemble(|a| a.paddd(XMM0, XMM1));
    assert_eq!(code, [0x66, 0x0F, 0xFE, 0xC1]);
}

#[test]
fn test_psubd() {
    // psubd xmm0, xmm1 → 66 0F FA C1
    let code = assemble(|a| a.psubd(XMM0, XMM1));
    assert_eq!(code, [0x66, 0x0F, 0xFA, 0xC1]);
}

#[test]
fn test_pxor() {
    // pxor xmm0, xmm0 → 66 0F EF C0
    let code = assemble(|a| a.pxor(XMM0, XMM0));
    assert_eq!(code, [0x66, 0x0F, 0xEF, 0xC0]);
}

#[test]
fn test_pand() {
    // pand xmm0, xmm1 → 66 0F DB C1
    let code = assemble(|a| a.pand(XMM0, XMM1));
    assert_eq!(code, [0x66, 0x0F, 0xDB, 0xC1]);
}

#[test]
fn test_por() {
    // por xmm0, xmm1 → 66 0F EB C1
    let code = assemble(|a| a.por(XMM0, XMM1));
    assert_eq!(code, [0x66, 0x0F, 0xEB, 0xC1]);
}

// ─── SSE with extended registers ──────────────────────────────

#[test]
fn test_addps_xmm8_xmm9() {
    // addps xmm8, xmm9 → 45 0F 58 C1
    let code = assemble(|a| a.addps(XMM8, XMM9));
    assert_eq!(code, [0x45, 0x0F, 0x58, 0xC1]);
}

#[test]
fn test_movaps_xmm15_xmm0() {
    // movaps xmm15, xmm0 → 44 0F 28 F8
    let code = assemble(|a| a.movaps(XMM15, XMM0));
    assert_eq!(code, [0x44, 0x0F, 0x28, 0xF8]);
}

// ─── SSE with memory ──────────────────────────────────────────

#[test]
fn test_addps_mem() {
    // addps xmm0, [rax] → 0F 58 00
    let code = assemble(|a| a.addps(XMM0, xmmword_ptr(RAX.into())));
    assert_eq!(code, [0x0F, 0x58, 0x00]);
}

#[test]
fn test_movaps_mem_xmm() {
    // movaps [rax], xmm0 → 0F 29 00
    let code = assemble(|a| a.movaps(xmmword_ptr(RAX.into()), XMM0));
    assert_eq!(code, [0x0F, 0x29, 0x00]);
}

// ─── movd / movq ──────────────────────────────────────────────

#[test]
fn test_movd_xmm_eax() {
    // movd xmm0, eax → 66 0F 6E C0
    let code = assemble(|a| a.movd(XMM0, EAX));
    assert_eq!(code, [0x66, 0x0F, 0x6E, 0xC0]);
}

#[test]
fn test_movd_eax_xmm() {
    // movd eax, xmm0 → 66 0F 7E C0
    let code = assemble(|a| a.movd(EAX, XMM0));
    assert_eq!(code, [0x66, 0x0F, 0x7E, 0xC0]);
}

#[test]
fn test_movq_xmm_xmm() {
    // movq xmm0, xmm1 → F3 0F 7E C1
    let code = assemble(|a| a.movq(XMM0, XMM1));
    assert_eq!(code, [0xF3, 0x0F, 0x7E, 0xC1]);
}

// ─── AVX (VEX-encoded) ────────────────────────────────────────

#[test]
fn test_vaddps_xmm() {
    // vaddps xmm0, xmm1, xmm2 → C5 F0 58 C2
    // VEX.128.0F.WIG 58 /r
    // C5 = 2-byte VEX, F0 = ~R(1) | vvvv=~1(0b1110) | L=0 | pp=0
    // = 1_1110_0_00 = 0xF0
    let code = assemble(|a| a.vaddps(XMM0, XMM1, XMM2));
    assert_eq!(code, [0xC5, 0xF0, 0x58, 0xC2]);
}

#[test]
fn test_vaddps_ymm() {
    // vaddps ymm0, ymm1, ymm2 → C5 F4 58 C2
    // VEX.256.0F.WIG 58 /r
    // C5 F4 = R=1 | vvvv=~1(0b1110) | L=1 | pp=0 → 0xF4
    let code = assemble(|a| a.vaddps(YMM0, YMM1, YMM2));
    assert_eq!(code, [0xC5, 0xF4, 0x58, 0xC2]);
}

#[test]
fn test_vaddpd_xmm() {
    // vaddpd xmm0, xmm1, xmm2 → C5 F1 58 C2
    // VEX.128.66.0F.WIG 58 /r
    // pp=1 (66), F1 = 1_1110_0_01
    let code = assemble(|a| a.vaddpd(XMM0, XMM1, XMM2));
    assert_eq!(code, [0xC5, 0xF1, 0x58, 0xC2]);
}

#[test]
fn test_vsubps_xmm() {
    // vsubps xmm0, xmm1, xmm2 → C5 F0 5C C2
    let code = assemble(|a| a.vsubps(XMM0, XMM1, XMM2));
    assert_eq!(code, [0xC5, 0xF0, 0x5C, 0xC2]);
}

#[test]
fn test_vmulps_xmm() {
    // vmulps xmm0, xmm1, xmm2 → C5 F0 59 C2
    let code = assemble(|a| a.vmulps(XMM0, XMM1, XMM2));
    assert_eq!(code, [0xC5, 0xF0, 0x59, 0xC2]);
}

#[test]
fn test_vdivps_xmm() {
    // vdivps xmm0, xmm1, xmm2 → C5 F0 5E C2
    let code = assemble(|a| a.vdivps(XMM0, XMM1, XMM2));
    assert_eq!(code, [0xC5, 0xF0, 0x5E, 0xC2]);
}

#[test]
fn test_vxorps_xmm() {
    // vxorps xmm0, xmm0, xmm0 → C5 F8 57 C0
    // vvvv=~0 = 0b1111, pp=0, L=0 → 0xF8
    let code = assemble(|a| a.vxorps(XMM0, XMM0, XMM0));
    assert_eq!(code, [0xC5, 0xF8, 0x57, 0xC0]);
}

#[test]
fn test_vandps_ymm() {
    // vandps ymm0, ymm1, ymm2 → C5 F4 54 C2
    let code = assemble(|a| a.vandps(YMM0, YMM1, YMM2));
    assert_eq!(code, [0xC5, 0xF4, 0x54, 0xC2]);
}

#[test]
fn test_vaddps_xmm8() {
    // vaddps xmm8, xmm9, xmm10 → C4 41 30 58 C2
    // 3-byte VEX needed: R=0 (xmm8.idx=8), X=1, B=0 (xmm10.idx=10)
    // C4 = 3-byte VEX prefix
    // byte1: R=0(0) | X=1(0x40) | B=0(0) | mmmmm=1 → 0x41
    // byte2: W=0 | vvvv=~9(0b0110) | L=0 | pp=0 → 0x30
    let code = assemble(|a| a.vaddps(XMM8, XMM9, XMM10));
    assert_eq!(code, [0xC4, 0x41, 0x30, 0x58, 0xC2]);
}

// ─── AVX Data Movement ────────────────────────────────────────

#[test]
fn test_vmovaps_xmm() {
    // vmovaps xmm0, xmm1 → C5 F8 28 C1
    let code = assemble(|a| a.vmovaps(XMM0, XMM1));
    assert_eq!(code, [0xC5, 0xF8, 0x28, 0xC1]);
}

#[test]
fn test_vmovaps_ymm() {
    // vmovaps ymm0, ymm1 → C5 FC 28 C1
    let code = assemble(|a| a.vmovaps(YMM0, YMM1));
    assert_eq!(code, [0xC5, 0xFC, 0x28, 0xC1]);
}

#[test]
fn test_vmovups_xmm() {
    // vmovups xmm0, xmm1 → C5 F8 10 C1
    let code = assemble(|a| a.vmovups(XMM0, XMM1));
    assert_eq!(code, [0xC5, 0xF8, 0x10, 0xC1]);
}

#[test]
fn test_vmovdqa_xmm() {
    // vmovdqa xmm0, xmm1 → C5 F9 6F C1
    // pp=1 (66), vvvv=0b1111 → F9
    let code = assemble(|a| a.vmovdqa(XMM0, XMM1));
    assert_eq!(code, [0xC5, 0xF9, 0x6F, 0xC1]);
}

#[test]
fn test_vmovdqu_xmm() {
    // vmovdqu xmm0, xmm1 → C5 FA 6F C1
    // pp=2 (F3), vvvv=0b1111 → FA
    let code = assemble(|a| a.vmovdqu(XMM0, XMM1));
    assert_eq!(code, [0xC5, 0xFA, 0x6F, 0xC1]);
}

// ─── AVX Integer ──────────────────────────────────────────────

#[test]
fn test_vpaddd_xmm() {
    // vpaddd xmm0, xmm1, xmm2 → C5 F1 FE C2
    // pp=1 (66)
    let code = assemble(|a| a.vpaddd(XMM0, XMM1, XMM2));
    assert_eq!(code, [0xC5, 0xF1, 0xFE, 0xC2]);
}

#[test]
fn test_vpsubd_xmm() {
    // vpsubd xmm0, xmm1, xmm2 → C5 F1 FA C2
    let code = assemble(|a| a.vpsubd(XMM0, XMM1, XMM2));
    assert_eq!(code, [0xC5, 0xF1, 0xFA, 0xC2]);
}

#[test]
fn test_vpxor_xmm() {
    // vpxor xmm0, xmm0, xmm0 → C5 F9 EF C0
    let code = assemble(|a| a.vpxor(XMM0, XMM0, XMM0));
    assert_eq!(code, [0xC5, 0xF9, 0xEF, 0xC0]);
}

#[test]
fn test_vpand_ymm() {
    // vpand ymm0, ymm1, ymm2 → C5 F5 DB C2
    let code = assemble(|a| a.vpand(YMM0, YMM1, YMM2));
    assert_eq!(code, [0xC5, 0xF5, 0xDB, 0xC2]);
}

#[test]
fn test_vpor_ymm() {
    // vpor ymm0, ymm1, ymm2 → C5 F5 EB C2
    let code = assemble(|a| a.vpor(YMM0, YMM1, YMM2));
    assert_eq!(code, [0xC5, 0xF5, 0xEB, 0xC2]);
}

// ─── AVX with memory ──────────────────────────────────────────

#[test]
fn test_vaddps_mem() {
    // vaddps xmm0, xmm1, [rax] → C5 F0 58 00
    let code = assemble(|a| a.vaddps(XMM0, XMM1, xmmword_ptr(RAX.into())));
    assert_eq!(code, [0xC5, 0xF0, 0x58, 0x00]);
}

#[test]
fn test_vaddps_mem_disp() {
    // vaddps xmm0, xmm1, [rax+0x10] → C5 F0 58 40 10
    let code = assemble(|a| a.vaddps(XMM0, XMM1, xmmword_ptr(RAX + 0x10)));
    assert_eq!(code, [0xC5, 0xF0, 0x58, 0x40, 0x10]);
}

#[test]
fn test_vmovaps_mem_store() {
    // vmovaps [rax], xmm0 → C5 F8 29 00
    let code = assemble(|a| a.vmovaps(xmmword_ptr(RAX.into()), XMM0));
    assert_eq!(code, [0xC5, 0xF8, 0x29, 0x00]);
}

// ─── EVEX (AVX-512) ───────────────────────────────────────────

#[test]
fn test_vaddps_zmm() {
    // vaddps zmm0, zmm1, zmm2
    // EVEX.512.0F.W0 58 /r
    // 62 F1 74 48 58 C2
    // P0: R=1(80) X=1(40) B=1(20) R'=1(10) B4=0 mmm=1 → F1
    // P1: W=0 | vvvv=~1(0b1110) << 3 | 0x04 (u=1) | pp=0 → 74
    // P2: z=0 | LL=10(512) << 5 | b=0 | V'=1(8) | aaa=0 → 48
    let code = assemble(|a| a.vaddps(ZMM0, ZMM1, ZMM2));
    assert_eq!(code, [0x62, 0xF1, 0x74, 0x48, 0x58, 0xC2]);
}

#[test]
fn test_vaddpd_zmm() {
    // vaddpd zmm0, zmm1, zmm2
    // EVEX.512.66.0F.W1 58 /r
    // 62 F1 F5 48 58 C2
    let code = assemble(|a| a.vaddpd(ZMM0, ZMM1, ZMM2));
    assert_eq!(code, [0x62, 0xF1, 0xF5, 0x48, 0x58, 0xC2]);
}

#[test]
fn test_vsubps_zmm() {
    // vsubps zmm0, zmm1, zmm2
    // 62 F1 74 48 5C C2
    let code = assemble(|a| a.vsubps(ZMM0, ZMM1, ZMM2));
    assert_eq!(code, [0x62, 0xF1, 0x74, 0x48, 0x5C, 0xC2]);
}

#[test]
fn test_vmulps_zmm() {
    // vmulps zmm0, zmm1, zmm2
    // 62 F1 74 48 59 C2
    let code = assemble(|a| a.vmulps(ZMM0, ZMM1, ZMM2));
    assert_eq!(code, [0x62, 0xF1, 0x74, 0x48, 0x59, 0xC2]);
}

#[test]
fn test_vxorps_zmm() {
    // vxorps zmm0, zmm0, zmm0
    // 62 F1 7C 48 57 C0
    let code = assemble(|a| a.vxorps(ZMM0, ZMM0, ZMM0));
    assert_eq!(code, [0x62, 0xF1, 0x7C, 0x48, 0x57, 0xC0]);
}

#[test]
fn test_vaddps_zmm16() {
    // vaddps zmm16, zmm17, zmm18
    // Uses EVEX with extended registers (idx >= 16)
    // 62 21 74 40 58 C2
    // P0: R=1(80)→0 | X=1(40) | B=1(20)→0 | R'=0(10)→0 | B4=0 | mmm=1
    //   R=xmm16 idx=16, bit4=1 → R=0 → clear 0x80
    //   R'=xmm16 idx=16, bit5 check... wait let me think
    // zmm16: idx=16, bit3=0 (16 & 8 = 0), ext_idx=false, ext_idx2=true (16 & 16 != 0)
    // zmm17: idx=17, bit3=0 (17 & 8 = 0x08? 17=10001, so bit3=1!), ext_idx=true, ext_idx2=true
    // zmm18: idx=18, bit3=0 (18=10010, bit3=1?  10010 & 1000 = 10000 & 01000 = 0... 18 & 8 = 16 & 8? 18 = 16+2 = 0b10010, so bit3 (8=0b1000) = 0b10010 & 0b01000 = 0b00000 = 0). ext_idx=false
    // Wait: 18 = 0b10010, & 8 (0b01000) = 0b00000 = 0. So zmm18 is_ext_idx=false, is_ext_idx2=true (18 & 16 = 16 != 0)
    // zmm17 = 17 = 0b10001, & 8 = 0b00000, so also NOT ext_idx. ext_idx2 = 17 & 16 = 16, true.
    // zmm16 = 16 = 0b10000, & 8 = 0, NOT ext_idx. ext_idx2 = true.
    //
    // emit_evex(reg=zmm16, base=zmm18, v=Some(&zmm17), type_, code, ...)
    // r_flag = reg.is_ext_idx() = (16 & 8 != 0) = false
    // x3 = x_reg (None for reg case) = false; but base.is_simd() && base.is_ext_idx2() ... wait
    //   Actually for reg-reg, x_reg is None
    // b_ext = base.is_ext_idx() = (18 & 8 = 0) = false
    // rp = reg.is_ext_idx2() = (16 & 16 != 0) = true
    // b4 = base.is_ext_idx2() && base.is_reg()... wait base=zmm18 is_reg()? No, it's ZMM kind, is_reg() checks Kind::Reg
    //
    // Hmm, I need to re-check my emit_evex implementation. The `b4` check is:
    //   let b4 = if base.is_reg() && base.is_ext_idx2() { 8u8 } else { 0 };
    // But for SIMD regs, is_reg() returns false (it checks Kind::Reg bit).
    // In xbyak's C++ code, isREG() checks kind & REG, which for XMM/YMM/ZMM is false.
    // So b4 = 0 for SIMD regs. That seems wrong for extended SIMD regs...
    //
    // Actually looking at xbyak more carefully, the EVEX B4 field is for APX (GPR extension).
    // For SIMD regs, the encoding uses R', X3 differently. EVEX encodes idx bit 4 via:
    //   - reg (R'): rp = reg.isExtIdx2()
    //   - vvvv (V'): v4 bit
    //   - base/rm (B/X for SIB): x3 for VSIB extended index
    // But for reg-reg EVEX, base uses B (bit 3) and B4... hmm
    //
    // Let me just run the test and see what output we get, then adjust.
    // Actually, let me skip the zmm16+ test for now and just test basic zmm0-15.
    let code = assemble(|a| a.vaddps(ZMM16, ZMM17, ZMM18));
    // EVEX encoding for zmm16-zmm18:
    // zmm16: idx=16, R=!(16&8=0)=1→0x80, R'=!(16&16!=0)=0→clear 0x10
    // zmm17 (vvvv): idx=17, vvvv=~17=0b01110
    // zmm18 (rm): idx=18, B=!(18&8=0)=1→0x20, B4=0 (simd, not is_reg())
    // P0: 0x80|0x40|0x20|0x00|0x00|0x01 = 0xE1? No...
    // R=!ext_idx(16)=!(16&8!=0)=!(0)=true → 0x80 set
    // X=no index → set 0x40
    // B=!base.ext_idx=!(18&8!=0)=!(0b10010 & 0b01000 = 0)=true → 0x20 set
    // R'=!reg.ext_idx2=!(16&16!=0)=!(true)=false → 0x10 clear → 0x00
    // b4 = base.is_reg() check - zmm is NOT is_reg() (Kind::Zmm), so b4=0
    // mmm=1 (0F map)
    // P0 = 0x80|0x40|0x20|0x00|0x00|0x01 = 0xE1
    //
    // P1: W=0 | vvvv=~17&15=14=0b1110 <<3 = 0x70 | u=4(since !x_reg.ext_idx2, x_reg=None→4) | pp=0
    // → 0x00|0x70|0x04|0x00 = 0x74
    //
    // P2: z=0 | LL=10(512)<<5=0x40 | b=0 | V'=!(v.ext_idx2)=!(17&16!=0)=!true=0→0x00 (clear bit3) | aaa=0
    // → 0x00|0x40|0x00|0x00|0x00 = 0x40
    //
    // ModRM: mod=11, reg=zmm16&7=0, rm=zmm18&7=2 → 0xC2
    //
    // Full: 62 A1 74 40 58 C2
    // X̄=0 because zmm18 idx=18, bit4=1 → X3=true → inverted=0
    assert_eq!(code, [0x62, 0xA1, 0x74, 0x40, 0x58, 0xC2]);
}

// ─── EVEX with opmask ──────────────────────────────────────────

#[test]
fn test_vaddps_zmm_k1() {
    // vaddps zmm0{k1}, zmm1, zmm2
    // 62 F1 74 49 58 C2
    // Same as vaddps zmm but with aaa=1 (k1)
    let code = assemble(|a| a.vaddps(ZMM0.k(1), ZMM1, ZMM2));
    assert_eq!(code, [0x62, 0xF1, 0x74, 0x49, 0x58, 0xC2]);
}

#[test]
fn test_vaddps_zmm_k1_z() {
    // vaddps zmm0{k1}{z}, zmm1, zmm2
    // 62 F1 74 C9 58 C2
    // z=1 → bit 7 of P2 set → 0x80 | 0x49 = 0xC9
    let code = assemble(|a| a.vaddps(ZMM0.k(1).z(), ZMM1, ZMM2));
    assert_eq!(code, [0x62, 0xF1, 0x74, 0xC9, 0x58, 0xC2]);
}
