use core::fmt;

/// All error types for rxbyak, mapped 1:1 from xbyak's error enum.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Error {
    BadAddressing,
    CodeIsTooBig,
    BadScale,
    EspCantBeIndex,
    BadCombination,
    BadSizeOfRegister,
    ImmIsTooBig,
    BadAlign,
    LabelIsRedefined,
    LabelIsTooFar,
    LabelIsNotFound,
    CodeIsNotCopyable,
    BadParameter,
    CantProtect,
    CantUse64BitDisp,
    OffsetIsTooBig,
    MemSizeIsNotSpecified,
    BadMemSize,
    BadStCombination,
    UnderLocalLabel,
    CantAlloc,
    OnlyTNearIsSupportedInAutoGrow,
    BadProtectMode,
    BadPnum,
    BadTnum,
    BadVsibAddressing,
    CantConvert,
    LabelIsNotSetByL,
    LabelIsAlreadySetByL,
    BadLabelStr,
    Munmap,
    OpmaskIsAlreadySet,
    RoundingIsAlreadySet,
    K0IsInvalid,
    EvexIsInvalid,
    SaeIsInvalid,
    ErIsInvalid,
    InvalidBroadcast,
    InvalidOpmaskWithMemory,
    InvalidZero,
    InvalidRipInAutoGrow,
    InvalidMibAddress,
    X2apicIsNotSupported,
    NotSupported,
    SameRegsAreInvalid,
    InvalidNf,
    InvalidZu,
    CantUseRex2,
    InvalidDfv,
    InvalidRegIdx,
    BadEncodingMode,
    CantUseAbcdh,
    CantInitCpuTopology,
    InvalidCpumaskIndex,
    Internal,
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::BadAddressing => write!(f, "bad addressing"),
            Error::CodeIsTooBig => write!(f, "code is too big"),
            Error::BadScale => write!(f, "bad scale"),
            Error::EspCantBeIndex => write!(f, "esp can't be index"),
            Error::BadCombination => write!(f, "bad combination"),
            Error::BadSizeOfRegister => write!(f, "bad size of register"),
            Error::ImmIsTooBig => write!(f, "immediate is too big"),
            Error::BadAlign => write!(f, "bad alignment"),
            Error::LabelIsRedefined => write!(f, "label is redefined"),
            Error::LabelIsTooFar => write!(f, "label is too far"),
            Error::LabelIsNotFound => write!(f, "label is not found"),
            Error::CodeIsNotCopyable => write!(f, "code is not copyable"),
            Error::BadParameter => write!(f, "bad parameter"),
            Error::CantProtect => write!(f, "can't protect memory"),
            Error::CantUse64BitDisp => write!(f, "can't use 64-bit displacement"),
            Error::OffsetIsTooBig => write!(f, "offset is too big"),
            Error::MemSizeIsNotSpecified => write!(f, "memory size is not specified"),
            Error::BadMemSize => write!(f, "bad memory size"),
            Error::BadStCombination => write!(f, "bad st combination"),
            Error::UnderLocalLabel => write!(f, "under local label"),
            Error::CantAlloc => write!(f, "can't allocate memory"),
            Error::OnlyTNearIsSupportedInAutoGrow => {
                write!(f, "only T_NEAR is supported in AutoGrow")
            }
            Error::BadProtectMode => write!(f, "bad protect mode"),
            Error::BadPnum => write!(f, "bad pnum"),
            Error::BadTnum => write!(f, "bad tnum"),
            Error::BadVsibAddressing => write!(f, "bad VSIB addressing"),
            Error::CantConvert => write!(f, "can't convert"),
            Error::LabelIsNotSetByL => write!(f, "label is not set by L()"),
            Error::LabelIsAlreadySetByL => write!(f, "label is already set by L()"),
            Error::BadLabelStr => write!(f, "bad label string"),
            Error::Munmap => write!(f, "munmap failed"),
            Error::OpmaskIsAlreadySet => write!(f, "opmask is already set"),
            Error::RoundingIsAlreadySet => write!(f, "rounding is already set"),
            Error::K0IsInvalid => write!(f, "k0 is invalid"),
            Error::EvexIsInvalid => write!(f, "EVEX is invalid"),
            Error::SaeIsInvalid => write!(f, "SAE is invalid"),
            Error::ErIsInvalid => write!(f, "ER is invalid"),
            Error::InvalidBroadcast => write!(f, "invalid broadcast"),
            Error::InvalidOpmaskWithMemory => write!(f, "invalid opmask with memory"),
            Error::InvalidZero => write!(f, "invalid zero"),
            Error::InvalidRipInAutoGrow => write!(f, "invalid RIP in AutoGrow"),
            Error::InvalidMibAddress => write!(f, "invalid MIB address"),
            Error::X2apicIsNotSupported => write!(f, "x2APIC is not supported"),
            Error::NotSupported => write!(f, "not supported"),
            Error::SameRegsAreInvalid => write!(f, "same registers are invalid"),
            Error::InvalidNf => write!(f, "invalid NF"),
            Error::InvalidZu => write!(f, "invalid ZU"),
            Error::CantUseRex2 => write!(f, "can't use REX2"),
            Error::InvalidDfv => write!(f, "invalid DFV"),
            Error::InvalidRegIdx => write!(f, "invalid register index"),
            Error::BadEncodingMode => write!(f, "bad encoding mode"),
            Error::CantUseAbcdh => write!(f, "can't use [abcd]h registers"),
            Error::CantInitCpuTopology => write!(f, "can't init CPU topology"),
            Error::InvalidCpumaskIndex => write!(f, "invalid CPU mask index"),
            Error::Internal => write!(f, "internal error"),
        }
    }
}

impl std::error::Error for Error {}

pub type Result<T> = std::result::Result<T, Error>;
